### ISSUE TITLE
Basic Setting

### ISSUE THREAD

**Issue by jaemin96** [jaemin96/Jaemin.kim#1]
## Summary
기존 Template project 세팅 정보 수정 작업

## Todo
- [x] Nextjs 사용환경 세팅하기
  - [x] 프로젝트 경로에 CNA 로 애플리케이션 생성
  - [x] 불필요한 파일 삭제 및 기본 세팅들 수정하기

- [x] package.json 수정 작업
   - [x] Template repo에서 설정되어 있는 기본 정보들 현 repo 정보로 업데이트

**Comment by jaemin96** [comment]
-[x] Complete Todos
