### ISSUE TITLE
사이드 레이아웃 구현

### ISSUE THREAD

**Issue by jaemin96** [jaemin96/Jaemin.kim#10]
## Summary
사이드 영역 구현

# Todo
- [x] 전체 레이아웃 설정 
- [x] 아이콘 | 프로필 이미지 추가
- [x] 소셜 링크 추가
- [x] 화면 모드 변경 버튼 추가
