### ISSUE TITLE
사이드 네비게이션 구현

### ISSUE THREAD

**Issue by jaemin96** [jaemin96/Jaemin.kim#12]
## Summary
사이드 영역에 현재 포커스가 되어있는 영역표시와 선택한 카테고리로 이동할 수 있는 네비게이션 기능 구현

## Todo
- [ ] 네비게이션 버튼 기획
- [ ] 네비게이션 스타일 기획
- [ ] 네비게이션 기능 구현
- [ ] 네비게이션 스타일 수정
