### ISSUE TITLE
프로젝트 커스텀 컬러 설정

### ISSUE THREAD

**Issue by jaemin96** [jaemin96/Jaemin.kim#13]
## Summary
다크모드 & 화이트모드 화면 모드 설정에 사용할 색상 설정

## Todo
- [x] 화이트모드 색상 조합 기획
- [x] 다크모드 색상 조합 기획
- [x] 사용할 색상 validation으로 설정
