### ISSUE TITLE
ExpandedItem 불필요한 반복 제거

### ISSUE THREAD

**Issue by jaemin96** [jaemin96/Jaemin.kim#20]
## Summary
ExpandedItem을 코드상에서 나열하는 방식에서 config 정보에서 불러와 나타내는 방식으로 수정

## Todo
- [x] skill config 파일 생성 후 기존 데이터 등록
- [x] skillDetail 모듈 컴포넌트 추가
- [x] skill config 파일의 정보를 호출하여 기존에 나열되어있는 ExpandedItem 반복 개선

### Later
기존 방식에서 카테고리 별로 Expand 또한 반복이 되고 있지만 Expand 코드 개선 작업 후에 생기는 사이드 이펙트를 고려하여 현재 해당 부분까지 수정하진 않을 계획
