### ISSUE TITLE
메타태그에 포함시킬 정보 기획

### ISSUE THREAD

**Issue by jaemin96** [jaemin96/Jaemin.kim#23]
## TODO
- [ ] favicon 추가
- [x] og image 추가
- [ ] 네이버 검색엔진 설정
- [ ] 구글 검색엔진 설정
