### ISSUE TITLE
페이지 리뉴얼

### ISSUE THREAD

**Issue by jaemin96** [jaemin96/Jaemin.kim#27]
## Summary
기존에 페이지 형식에서 새롭게 리뉴얼 작업 진행

## Todo
- [ ] 원페이지에서 모든 컨텐츠를 보여주던 방식에서 탭토글이나 페이지 전환 방식으로 수정
- [ ] 전체적인 컨텐츠 폰트 크기 키우기
- [ ] 리뉴얼 사용 컴포넌트 추가
