### ISSUE TITLE
Mobile 환경 - Header

### ISSUE THREAD

**Issue by jaemin96** [jaemin96/Jaemin.kim#8]
## Summary
모바일 환경에서 나타나게될 Header 작업

## Todo
- [ ] 햄버거버튼
  - [ ] 아이콘 추가
  - [ ] 버튼 토글기능 구현
  - [ ] 토글 on & off 상태관리
  
- [ ] 사이드 슬라이드 모달 구현
  - [ ] 우측에서 좌측
  - [ ] 전체 디바이스의 80%를 차지하도록
  - [ ] 모달외의 공간을 클릭 시 모달 사라지도록
  - [ ] 슬라이드 모달에 표시할 컨텐츠 표시
  - [ ] 전반적인 스타일링
  
- [ ] 햄버거 버튼과 슬라이드 모달 동작테스트

**Comment by jaemin96** [comment]
[2023. 06. 13]
버튼 토글 기능 구현
슬라이드 모달 on off 상태관리
슬라이드 모달 overlay & outside 클릭 시 상태 관리 기능 구현
