### ISSUE TITLE
Mobile - Home 화면

### ISSUE THREAD

**Issue by jaemin96** [jaemin96/Jaemin.kim#9]
## Summary
모바일 기기에서 보이는 Home 화면 작업 

## Todo
- [ ] 코멘트 작성 영역 
- [ ] 사용스펙 (언어, 프레임워크) 작성 영역
- [ ] 연락처 작성 영역
- [ ] 프로젝트 경력 (진행한 프로젝트 사용 스펙) 작성 영역
